# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title:  Nick's Data Blog
email: nickb@everlane.com
description: >- # this means to ignore newlines until "baseurl:"
  Data Science and Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://benthem.io" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: NickBenthem
# github_username:  NickBenthem

# Build settings
markdown: kramdown
#remote_theme: "mmistakes/so-simple-theme@3.2.0"

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-auto-image
  - jekyll-figure


copyright: "Let me know if you found something useful: NicholasBenthem {{at}} gmail.com"

author:
  name: Nick Benthem
  twitter: NickBenthem
  picture: /assets/img/NickPhoto.jpeg

#logo: https://media-exp1.licdn.com/dms/image/C4D03AQFcAnCXLYfSzA/profile-displayphoto-shrink_200_200/0?e=1584576000&v=beta&t=vecSnrxt3SprcPSm70_2cziEMamfCmt0XFpi_hy742s

# defaults:
#   - scope:
#       path: ""
#     values:
#       image: False

footer_links:
  - title: Twitter
    url: https://twitter.com/NickBenthem
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/NickBenthem
    icon: fab fa-github-square

paginate: 10  # amount of posts to show per page
paginate_path: /page:num/

search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

google_analytics: UA-156152306-1

skin: "/assets/css/skins/light.css"

read_time: true

google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
